#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate battle-tested Frida hook scripts for SSL unpinning, root bypass, crypto sniffing, and method tracing.

WHY THIS EXISTS
---------------
Writing Frida scripts from scratch during live triage is error-prone and time-consuming. Common
reversing tasks (bypassing SSL pinning, defeating root detection, intercepting cryptographic keys,
or tracing specific method calls with parameter inspection) follow standard, battle-tested patterns.

This script outputs modular, ready-to-run Frida JavaScript files tailored to the target app or
specific class/method names.

TEMPLATES
---------
  * ssl-unpin       Universal SSL/TLS pinning bypass (OkHttp, TrustManager, NetworkSecurityConfig, WebView)
  * root-bypass     Root detection bypass (RootBeer, su binary presence, test-keys, package managers)
  * crypto-monitor  Real-time interception of AES, RSA, DES, HMAC, and MessageDigest keys/data
  * method-trace    Trace any Java method: dumps arguments, return values, and stack traces
  * intent-monitor  Monitor startActivity, broadcast intents, and dump Bundle key-values

USAGE
-----
  # Generate SSL unpinning script
  python frida_hook_gen.py --template ssl-unpin --out ssl_bypass.js

  # Generate root detection bypass script
  python frida_hook_gen.py --template root-bypass --out root_bypass.js

  # Generate crypto API monitor
  python frida_hook_gen.py --template crypto-monitor --out crypto_trace.js

  # Generate custom method tracer
  python frida_hook_gen.py --template method-trace --class-name "com.target.auth.LoginManager" --method-name "verifyToken" --out trace.js

EXIT CODES
----------
  0 = script generated successfully
  2 = usage or argument error
"""

import argparse
import os
import sys

TEMPLATES = {
    "ssl-unpin": r"""/**
 * Universal Android SSL Pinning Bypass
 * Generated by frida_hook_gen.py
 */
Java.perform(function() {
    console.log("[*] Mengaktifkan Universal SSL Pinning Bypass...");

    // 1. javax.net.ssl.TrustManager
    try {
        var X509TrustManager = Java.use('javax.net.ssl.X509TrustManager');
        var SSLContext = Java.use('javax.net.ssl.SSLContext');
        var TrustManager = Java.registerClass({
            name: 'com.antigravity.ssl.TrustManager',
            implements: [X509TrustManager],
            methods: {
                checkClientTrusted: function(chain, authType) {},
                checkServerTrusted: function(chain, authType) {},
                getAcceptedIssuers: function() { return []; }
            }
        });
        var trustManagers = [TrustManager.$new()];
        var SSLContext_init = SSLContext.init.overload(
            '[Ljavax.net.ssl.KeyManager;', '[Ljavax.net.ssl.TrustManager;', 'java.security.SecureRandom');
        SSLContext_init.implementation = function(km, tm, sr) {
            console.log("[+] SSLContext.init bypass triggered");
            SSLContext_init.call(this, km, trustManagers, sr);
        };
    } catch(e) {}

    // 2. OkHttp 3 & 4
    try {
        var OkHttp3_CertPinner = Java.use('okhttp3.CertificatePinner');
        OkHttp3_CertPinner.check.overload('java.lang.String', 'java.util.List').implementation = function(str, list) {
            console.log("[+] OkHttp3 CertificatePinner check bypassed: " + str);
            return;
        };
    } catch(e) {}

    // 3. NetworkSecurityConfig
    try {
        var NetworkSecurityTrustManager = Java.use('android.security.net.config.NetworkSecurityTrustManager');
        NetworkSecurityTrustManager.checkPins.implementation = function(pins) {
            console.log("[+] NetworkSecurityTrustManager.checkPins bypassed");
            return;
        };
    } catch(e) {}

    console.log("[+] SSL Pinning bypass aktif.");
});
""",

    "root-bypass": r"""/**
 * Universal Android Root Detection Bypass
 * Generated by frida_hook_gen.py
 */
Java.perform(function() {
    console.log("[*] Mengaktifkan Universal Root Detection Bypass...");

    // 1. File checks (su, busybox, magisk, etc.)
    var File = Java.use("java.io.File");
    File.exists.implementation = function() {
        var path = this.getAbsolutePath();
        var blocked = ["/system/bin/su", "/system/xbin/su", "/sbin/su", "/system/app/Superuser.apk",
                       "/system/etc/init.d/99SuperSUDaemon", "/data/local/su", "/data/local/bin/su",
                       "/system/bin/.ext/.su", "/system/usr/we-need-root/su-backup"];
        for (var i = 0; i < blocked.length; i++) {
            if (path.indexOf(blocked[i]) !== -1) {
                console.log("[+] File.exists() palsu (false) untuk: " + path);
                return false;
            }
        }
        return this.exists();
    };

    // 2. Runtime.exec checks
    var Runtime = Java.use("java.lang.Runtime");
    Runtime.exec.overload('java.lang.String').implementation = function(cmd) {
        if (cmd.indexOf("su") !== -1 || cmd.indexOf("which") !== -1 || cmd.indexOf("busybox") !== -1) {
            console.log("[+] Runtime.exec() diblokir untuk perintah root: " + cmd);
            return Runtime.exec.call(this, "echo_blocked_command");
        }
        return this.exec(cmd);
    };

    // 3. Build tags (test-keys)
    var Build = Java.use("android.os.Build");
    Build.TAGS.value = "release-keys";

    console.log("[+] Root detection bypass aktif.");
});
""",

    "crypto-monitor": r"""/**
 * Android Cryptography Monitor (AES, RSA, DES, KeySpec, MessageDigest)
 * Generated by frida_hook_gen.py
 */
Java.perform(function() {
    console.log("[*] Memulai pemantauan Cryptography API...");

    function bytesToHex(bytes) {
        if (!bytes) return "null";
        var hex = "";
        for (var i = 0; i < bytes.length; i++) {
            var b = bytes[i] & 0xFF;
            hex += (b < 16 ? "0" : "") + b.toString(16);
        }
        return hex;
    }

    function bytesToString(bytes) {
        if (!bytes) return "null";
        try {
            var String = Java.use("java.lang.String");
            return String.$new(bytes).toString();
        } catch(e) {
            return "<binary>";
        }
    }

    // 1. SecretKeySpec
    try {
        var SecretKeySpec = Java.use("javax.crypto.spec.SecretKeySpec");
        SecretKeySpec.$init.overload('[B', 'java.lang.String').implementation = function(keyBytes, algorithm) {
            console.log("\n[🔑 KEY] SecretKeySpec Init:");
            console.log("  Algorithm : " + algorithm);
            console.log("  Key (Hex) : " + bytesToHex(keyBytes));
            console.log("  Key (Str) : " + bytesToString(keyBytes));
            return this.$init(keyBytes, algorithm);
        };
    } catch(e) {}

    // 2. Cipher.doFinal
    try {
        var Cipher = Java.use("javax.crypto.Cipher");
        Cipher.doFinal.overload('[B').implementation = function(input) {
            var output = this.doFinal(input);
            console.log("\n[🔒 CIPHER] Cipher.doFinal(" + this.getAlgorithm() + "):");
            console.log("  Input (Hex)  : " + bytesToHex(input));
            console.log("  Input (Str)  : " + bytesToString(input));
            console.log("  Output (Hex) : " + bytesToHex(output));
            return output;
        };
    } catch(e) {}

    // 3. MessageDigest.digest
    try {
        var MessageDigest = Java.use("java.security.MessageDigest");
        MessageDigest.digest.overload('[B').implementation = function(input) {
            var hash = this.digest(input);
            console.log("\n[#️⃣ HASH] MessageDigest.digest(" + this.getAlgorithm() + "):");
            console.log("  Input (Str) : " + bytesToString(input));
            console.log("  Hash (Hex)  : " + bytesToHex(hash));
            return hash;
        };
    } catch(e) {}
});
""",

    "intent-monitor": r"""/**
 * Android Intent & Bundle Monitor
 * Generated by frida_hook_gen.py
 */
Java.perform(function() {
    console.log("[*] Memulai pemantauan Intent & Bundle...");

    var Activity = Java.use("android.app.Activity");
    Activity.startActivity.overload('android.content.Intent').implementation = function(intent) {
        console.log("\n[🚀 INTENT] startActivity:");
        console.log("  Action : " + intent.getAction());
        console.log("  Data   : " + intent.getDataString());
        console.log("  Comp   : " + intent.getComponent());
        var extras = intent.getExtras();
        if (extras) {
            console.log("  Extras : " + extras.toString());
        }
        this.startActivity(intent);
    };
});
"""
}


def generate_method_trace(class_name: str, method_name: str) -> str:
    """Generate dynamic trace code for a specific class and method."""
    return f"""/**
 * Dynamic Method Tracer for {class_name}.{method_name}
 * Generated by frida_hook_gen.py
 */
Java.perform(function() {{
    console.log("[*] Memasang hook pada: {class_name}.{method_name}");

    try {{
        var targetClass = Java.use("{class_name}");
        var methods = targetClass["{method_name}"].overloads;

        methods.forEach(function(overload) {{
            overload.implementation = function() {{
                console.log("\n[🎯 METHOD CALL] {class_name}.{method_name}()");

                // Dump arguments
                for (var i = 0; i < arguments.length; i++) {{
                    try {{
                        console.log("  Arg[" + i + "]: " + arguments[i]);
                    }} catch(e) {{
                        console.log("  Arg[" + i + "]: [Cannot stringify]");
                    }}
                }}

                // Call original
                var result = overload.apply(this, arguments);
                try {{
                    console.log("  Result : " + result);
                }} catch(e) {{
                    console.log("  Result : [Object]");
                }}

                return result;
            }};
        }});
        console.log("[+] Hook berhasil terpasang pada seluruh overload {method_name}");
    }} catch(e) {{
        console.log("[-] Gagal hook {class_name}: " + e.message);
    }}
}});
"""


def main():
    parser = argparse.ArgumentParser(
        prog="frida_hook_gen.py",
        description="Generate ready-to-use Frida scripts for SSL unpinning, root bypass, crypto, and method tracing",
    )
    parser.add_argument(
        "--template", "-t",
        choices=["ssl-unpin", "root-bypass", "crypto-monitor", "method-trace", "intent-monitor"],
        default="ssl-unpin",
        help="Template hook yang akan dibuat"
    )
    parser.add_argument("--class-name", "-c", help="Nama class lengkap (contoh: com.app.auth.LoginService)")
    parser.add_argument("--method-name", "-m", help="Nama method target untuk di-trace")
    parser.add_argument("--out", "-o", help="File output JavaScript hasil generate")
    parser.add_argument("--print-only", action="store_true", help="Cetak skrip ke terminal tanpa simpan ke file")

    args = parser.parse_args()

    if args.template == "method-trace":
        if not args.class_name or not args.method_name:
            print("[ERROR] Template 'method-trace' memerlukan argumen --class-name dan --method-name")
            sys.exit(2)
        code = generate_method_trace(args.class_name, args.method_name)
    else:
        code = TEMPLATES.get(args.template, "")

    if args.print_only or not args.out:
        print(code)
    else:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[+] Skrip Frida ({args.template}) berhasil disimpan ke: {args.out}")

    sys.exit(0)


if __name__ == "__main__":
    main()
