#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract, demangle, and generate Frida hooks for exported JNI functions in native .so libraries.

WHY THIS EXISTS
---------------
Android apps frequently offload critical business logic, security verifications, and cryptographic
routines to native shared libraries (`.so`) using JNI (Java Native Interface).

JNI functions either use explicit dynamic registration (`RegisterNatives` inside `JNI_OnLoad`) or
standard exported symbol naming conventions:
  `Java_<package>_<class>_<method>`

Reversing these manually requires opening IDA/Ghidra, inspecting export tables, demangling JNI
escaped identifiers (`_1` -> `_`, `_2` -> `;`, `_3` -> `[`), and writing boilerplate Frida
interceptor scripts for each export.

This script:
  1. Inspects the ELF symbol table of any `.so` binary (arm64, armv7, x86).
  2. Identifies all exported JNI functions and JNI lifecycle entries (`JNI_OnLoad`).
  3. Demangles JNI symbol names into their Java class and method equivalents.
  4. Generates instant Frida native interceptor code to hook arguments, return values, and memory buffers.

USAGE
-----
  # Inspect exported JNI functions in a native library
  python jni_export_resolve.py --so libnative-lib.so

  # Generate Frida hooks for all JNI exports
  python jni_export_resolve.py --so libnative-lib.so --generate-hooks --out hook_jni.js

  # Output in structured JSON format
  python jni_export_resolve.py --so libnative-lib.so --json

EXIT CODES
----------
  0 = JNI exports found and processed
  1 = no JNI exports found in target library
  2 = usage or argument error
"""

import argparse
import json
import os
import re
import struct
import sys


def demangle_jni(symbol: str) -> dict:
    """Demangle Java_<pkg>_<class>_<method> into readable package, class, method."""
    if symbol in ("JNI_OnLoad", "JNI_OnUnload"):
        return {"type": "lifecycle", "name": symbol, "java_sig": symbol}

    if not symbol.startswith("Java_"):
        return {"type": "native_export", "name": symbol, "java_sig": symbol}

    raw = symbol[5:]  # strip 'Java_'

    # Unescape JNI sequences
    # _1 -> _
    # _2 -> ;
    # _3 -> [
    parts = raw.split("_")
    unescaped_parts = []
    i = 0
    while i < len(parts):
        part = parts[i]
        part = part.replace("_1", "_").replace("_2", ";").replace("_3", "[")
        unescaped_parts.append(part)
        i += 1

    if len(unescaped_parts) >= 2:
        method_name = unescaped_parts[-1]
        class_parts = unescaped_parts[:-1]
        class_name = ".".join(class_parts)
    else:
        method_name = raw
        class_name = "Unknown"

    return {
        "type": "jni_function",
        "symbol": symbol,
        "class_name": class_name,
        "method_name": method_name,
        "java_sig": f"{class_name}.{method_name}()"
    }


def extract_elf_symbols(so_path: str) -> list[str]:
    """Parse ELF binary symbols statically without external dependencies."""
    symbols = []
    with open(so_path, "rb") as f:
        data = f.read()

    if not data.startswith(b"\x7fELF"):
        raise ValueError(f"Bukan file ELF yang valid: {so_path}")

    # Heuristic string extractor for fast export table resolution
    # Matches symbols starting with Java_ or JNI_
    pattern = re.compile(rb'\b(Java_[A-Za-z0-9_]+|JNI_OnLoad|JNI_OnUnload)\b')
    for match in pattern.finditer(data):
        sym = match.group(1).decode("utf-8", errors="ignore")
        if sym not in symbols:
            symbols.append(sym)

    return symbols


def generate_frida_interceptor(so_name: str, jni_entries: list[dict]) -> str:
    """Generate ready-to-run Frida native interceptor code for the discovered symbols."""
    hooks = []
    for entry in jni_entries:
        sym = entry.get("symbol") or entry.get("name")
        sig = entry.get("java_sig", sym)

        hooks.append(f"""
    // Hook: {sig}
    var p_{sym} = Module.findExportByName("{so_name}", "{sym}");
    if (p_{sym}) {{
        Interceptor.attach(p_{sym}, {{
            onEnter: function(args) {{
                console.log("\\n[⚡ NATIVE JNI] {sig} dipanggil!");
                console.log("  JNIEnv* : " + args[0]);
                console.log("  jobject : " + args[1]);
                if (args[2]) {{
                    console.log("  Arg[2]  : " + args[2]);
                }}
            }},
            onLeave: function(retval) {{
                console.log("  Return  : " + retval);
            }}
        }});
        console.log("[+] Hooked: {sym}");
    }}
""")

    script = f"""/**
 * Auto-generated Frida Native Interceptor for {so_name}
 * Generated by jni_export_resolve.py
 */
Java.perform(function() {{
    console.log("[*] Memasang hook pada native library: {so_name}...");
{''.join(hooks)}
    console.log("[*] Hook native JNI selesai dipasang.");
}});
"""
    return script


def main():
    parser = argparse.ArgumentParser(
        prog="jni_export_resolve.py",
        description="Inspect and demangle JNI symbols in .so files and generate Frida interceptors",
    )
    parser.add_argument("--so", required=True, help="Path ke file library native .so")
    parser.add_argument("--generate-hooks", action="store_true", help="Generate kode Frida native interceptor")
    parser.add_argument("--out", "-o", help="File output untuk skrip Frida")
    parser.add_argument("--json", action="store_true", help="Output dalam format JSON")

    args = parser.parse_args()

    if not os.path.isfile(args.so):
        print(f"[ERROR] File .so tidak ditemukan: {args.so}")
        sys.exit(2)

    so_filename = os.path.basename(args.so)
    symbols = extract_elf_symbols(args.so)

    if not symbols:
        print(f"[-] Tidak ditemukan exported JNI symbols di {so_filename}")
        sys.exit(1)

    entries = [demangle_jni(s) for s in symbols]

    if args.generate_hooks:
        hook_code = generate_frida_interceptor(so_filename, entries)
        if args.out:
            with open(args.out, "w", encoding="utf-8") as f:
                f.write(hook_code)
            print(f"[+] Skrip Frida Interceptor disimpan ke: {args.out}")
        else:
            print(hook_code)
        sys.exit(0)

    if args.json:
        print(json.dumps(entries, indent=2))
    else:
        print(f"\n{'='*65}")
        print(f"  🔍 EXPORTED JNI SYMBOLS: {so_filename}")
        print(f"{'='*65}")
        print(f"  Ditemukan: {len(entries)} simbol JNI\n")
        for e in entries:
            t = e.get("type")
            if t == "lifecycle":
                print(f"  [LIFECYCLE] {e['name']}")
            elif t == "jni_function":
                print(f"  [JNI FUNC]  {e['java_sig']}")
                print(f"              └─ Symbol: {e['symbol']}")
            else:
                print(f"  [NATIVE]    {e['name']}")
        print(f"\n{'='*65}\n")

    sys.exit(0)


if __name__ == "__main__":
    main()
