#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate and manage runtime Frida cryptographic hooks for AES, RSA, HMAC, and Keystore.

WHY THIS EXISTS
---------------
Hardcoded keys, dynamic session encryption, and HMAC request signing are notoriously tricky
to recover from static decompilation alone when classes are obfuscated with DexGuard, ProGuard,
or native JNI logic.

Intercepting cryptographic operations at the Java runtime layer (JCA - Java Cryptography
Architecture) immediately exposes:
  - Symmetric keys (`SecretKeySpec`, `IvParameterSpec`)
  - Plaintext and ciphertext buffers (`Cipher.doFinal`, `Cipher.update`)
  - Hash payloads (`MessageDigest.digest`)
  - Android KeyStore aliases and operations

USAGE
-----
  # Generate crypto monitor script
  python crypto_monitor.py --out trace_crypto.js

  # Include stack trace for every cipher operation
  python crypto_monitor.py --stack-trace --out trace_crypto.js

EXIT CODES
----------
  0 = completed successfully
  2 = usage or argument error
"""

import argparse
import sys

CRYPTO_MONITOR_TEMPLATE = r"""/**
 * Android Cryptography Interceptor & Key Logger
 * Generated by crypto_monitor.py
 */
Java.perform(function() {
    console.log("[*] [CryptoMonitor] Memulai interceptor Java Cryptography Architecture (JCA)...");

    var showStack = {SHOW_STACK};

    function bytesToHex(bytes) {
        if (!bytes) return "null";
        var hex = "";
        for (var i = 0; i < bytes.length; i++) {
            var b = bytes[i] & 0xFF;
            hex += (b < 16 ? "0" : "") + b.toString(16);
        }
        return hex;
    }

    function bytesToString(bytes) {
        if (!bytes) return "null";
        try {
            var String = Java.use("java.lang.String");
            return String.$new(bytes).toString();
        } catch(e) {
            return "<binary>";
        }
    }

    function printStack() {
        if (!showStack) return;
        var Log = Java.use("android.util.Log");
        var Exception = Java.use("java.lang.Exception");
        console.log("  Stack:\n" + Log.getStackTraceString(Exception.$new()));
    }

    // 1. SecretKeySpec
    try {
        var SecretKeySpec = Java.use("javax.crypto.spec.SecretKeySpec");
        SecretKeySpec.$init.overload('[B', 'java.lang.String').implementation = function(keyBytes, algorithm) {
            console.log("\n[🔑 KEY] SecretKeySpec Init:");
            console.log("  Algorithm : " + algorithm);
            console.log("  Key (Hex) : " + bytesToHex(keyBytes));
            console.log("  Key (Str) : " + bytesToString(keyBytes));
            printStack();
            return this.$init(keyBytes, algorithm);
        };
    } catch(e) {}

    // 2. IvParameterSpec
    try {
        var IvParameterSpec = Java.use("javax.crypto.spec.IvParameterSpec");
        IvParameterSpec.$init.overload('[B').implementation = function(ivBytes) {
            console.log("\n[🎲 IV] IvParameterSpec Init:");
            console.log("  IV (Hex)  : " + bytesToHex(ivBytes));
            console.log("  IV (Str)  : " + bytesToString(ivBytes));
            return this.$init(ivBytes);
        };
    } catch(e) {}

    // 3. Cipher.doFinal
    try {
        var Cipher = Java.use("javax.crypto.Cipher");
        Cipher.doFinal.overload('[B').implementation = function(input) {
            var output = this.doFinal(input);
            console.log("\n[🔒 CIPHER] Cipher.doFinal(" + this.getAlgorithm() + "):");
            console.log("  Input (Hex)  : " + bytesToHex(input));
            console.log("  Input (Str)  : " + bytesToString(input));
            console.log("  Output (Hex) : " + bytesToHex(output));
            printStack();
            return output;
        };
    } catch(e) {}

    // 4. Mac.doFinal (HMAC)
    try {
        var Mac = Java.use("javax.crypto.Mac");
        Mac.doFinal.overload('[B').implementation = function(input) {
            var output = this.doFinal(input);
            console.log("\n[✍️ HMAC] Mac.doFinal(" + this.getAlgorithm() + "):");
            console.log("  Input (Str)  : " + bytesToString(input));
            console.log("  Output (Hex) : " + bytesToHex(output));
            return output;
        };
    } catch(e) {}

    console.log("[+] [CryptoMonitor] Interceptor crypto aktif.");
});
"""


def main():
    parser = argparse.ArgumentParser(
        prog="crypto_monitor.py",
        description="Generate runtime Frida cryptographic monitoring scripts",
    )
    parser.add_argument("--out", "-o", help="File output JavaScript hasil generate")
    parser.add_argument("--stack-trace", action="store_true", help="Sertakan stack trace untuk setiap operasi kripto")

    args = parser.parse_args()

    code = CRYPTO_MONITOR_TEMPLATE.replace("{SHOW_STACK}", "true" if args.stack_trace else "false")

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[+] Skrip crypto monitor disimpan ke: {args.out}")
    else:
        print(code)

    sys.exit(0)


if __name__ == "__main__":
    main()
