#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Frida hooks for native JNI functions and JNIEnv method calls.

WHY THIS EXISTS
---------------
Native code reversing frequently requires observing data crossing the JNI boundary:
  - Strings passed into C/C++ via `GetStringUTFChars`
  - Byte arrays passed into native encryption routines via `GetByteArrayElements`
  - Java callbacks invoked from C/C++ via `CallVoidMethod` or `CallObjectMethod`

Writing these Frida Interceptor and JNIEnv hooks manually requires complex boilerplate.
This script generates clean, robust JNI boundary interceptors ready for injection.

USAGE
-----
  # Generate JNIEnv string tracer
  python jni_hook_scaffold.py --mode env-strings --out jni_env_trace.js

  # Generate hook for a specific native function in a .so library
  python jni_hook_scaffold.py --so libnative.so --func Java_com_target_Security_checkLicense --out hook_license.js

EXIT CODES
----------
  0 = completed successfully
  2 = usage or argument error
"""

import argparse
import sys

JNI_ENV_STRINGS_HOOK = r"""/**
 * JNIEnv String & Method Boundary Tracer
 * Generated by jni_hook_scaffold.py
 */
Java.perform(function() {
    console.log("[*] [JNI Tracer] Memasang hook pada JNIEnv...");

    // Hook JNIEnv NewStringUTF
    var env = Java.vm.getEnv();
    var pNewStringUTF = env.handle.readPointer().add(Process.pointerSize * 167).readPointer();
    Interceptor.attach(pNewStringUTF, {
        onEnter: function(args) {
            try {
                var c_str = Memory.readCString(args[1]);
                if (c_str && c_str.length > 2) {
                    console.log("[JNI NewStringUTF] " + c_str);
                }
            } catch(e) {}
        }
    });

    console.log("[+] Hook JNIEnv NewStringUTF aktif.");
});
"""


def generate_func_hook(so_name: str, func_name: str) -> str:
    return f"""/**
 * JNI Native Function Hook: {func_name} in {so_name}
 * Generated by jni_hook_scaffold.py
 */
Java.perform(function() {{
    console.log("[*] Mencari simbol {func_name} di {so_name}...");
    var pFunc = Module.findExportByName("{so_name}", "{func_name}");
    if (!pFunc) {{
        console.log("[-] Simbol {func_name} tidak ditemukan di export table.");
        return;
    }}

    Interceptor.attach(pFunc, {{
        onEnter: function(args) {{
            console.log("\\n[⚡ NATIVE ENTER] {func_name}()");
            console.log("  JNIEnv* : " + args[0]);
            console.log("  jobject : " + args[1]);
            for (var i = 2; i < 6; i++) {{
                if (args[i]) {{
                    console.log("  Arg[" + i + "]  : " + args[i]);
                }}
            }}
        }},
        onLeave: function(retval) {{
            console.log("  Return  : " + retval);
            console.log("[⚡ NATIVE LEAVE] {func_name}()");
        }}
    }});
    console.log("[+] Interceptor berhasil dipasang pada {func_name}");
}});
"""


def main():
    parser = argparse.ArgumentParser(
        prog="jni_hook_scaffold.py",
        description="Generate Frida hooks for JNI functions and JNIEnv interactions",
    )
    parser.add_argument("--mode", choices=["env-strings", "custom"], default="env-strings", help="Mode scaffold hook")
    parser.add_argument("--so", help="Nama library .so target")
    parser.add_argument("--func", help="Nama fungsi native target")
    parser.add_argument("--out", "-o", help="File output JavaScript")

    args = parser.parse_args()

    if args.func:
        so = args.so or "libnative.so"
        code = generate_func_hook(so, args.func)
    else:
        code = JNI_ENV_STRINGS_HOOK

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[+] Skrip JNI hook disimpan ke: {args.out}")
    else:
        print(code)

    sys.exit(0)


if __name__ == "__main__":
    main()
