#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Android Runtime Cryptography Frida Hook Generator.

WHY THIS EXISTS
---------------
Static analysis can only reveal potential cryptographic flaws. To inspect the
actual keys, plaintexts, ciphertexts, and IVs used at runtime by an Android app,
dynamic instrumentation via Frida is essential.

This tool generates a robust, production-ready Frida instrumentation script that:
  1. Hooks javax.crypto.Cipher.init() to intercept Algorithm, Mode, Key, and IV.
  2. Hooks javax.crypto.Cipher.doFinal() to dump plaintext input & ciphertext output.
  3. Hooks javax.crypto.Mac to inspect HMAC keys and hashes.
  4. Hooks java.security.KeyStore to track alias access and key retrieval.
  5. Includes safety try-catch wrappers to prevent app crashes.

USAGE
-----
  # Generate Frida hook script to stdout
  python runtime_crypto_hook_gen.py

  # Save script to a file
  python runtime_crypto_hook_gen.py --out trace_crypto.js

  # Include native OpenSSL/BoringSSL hooks
  python runtime_crypto_hook_gen.py --out trace_crypto.js --native

EXIT CODES
----------
  0 = Script successfully generated
  2 = Usage or file write error
"""

import argparse
import sys

FRIDA_CRYPTO_TEMPLATE = r"""/**
 * Android Runtime Cryptography Interceptor (Frida)
 * Generated by Mobile Cryptography & Keystore Inspector
 */

Java.perform(function () {
    console.log("[*] Injected: Android Cryptography Runtime Monitor started...");

    var ByteString = Java.use("com.android.okhttp.okio.ByteString");
    function bytesToHex(bytes) {
        if (!bytes) return "null";
        var hex = "";
        for (var i = 0; i < bytes.length; i++) {
            var b = bytes[i] & 0xFF;
            hex += (b < 16 ? "0" : "") + b.toString(16);
        }
        return hex;
    }

    function bytesToString(bytes) {
        if (!bytes) return "null";
        try {
            var str = Java.use("java.lang.String").$new(bytes, "UTF-8");
            return str.toString();
        } catch (e) {
            return bytesToHex(bytes);
        }
    }

    // 1. Hook javax.crypto.Cipher
    var Cipher = Java.use("javax.crypto.Cipher");
    
    // Cipher.init overloads
    var initOverloads = Cipher.init.overloads;
    initOverloads.forEach(function (overload) {
        overload.implementation = function () {
            var mode = arguments[0]; // 1: ENCRYPT, 2: DECRYPT
            var key = arguments[1];
            var opMode = (mode === 1) ? "ENCRYPT" : ((mode === 2) ? "DECRYPT" : mode);

            console.log("\n[+] --- Cipher.init() ---");
            console.log("    Transformation : " + this.getAlgorithm());
            console.log("    Operation Mode : " + opMode);

            if (key) {
                try {
                    console.log("    Key Algorithm  : " + key.getAlgorithm());
                    console.log("    Key Format     : " + key.getFormat());
                    console.log("    Key Encoded Hex: " + bytesToHex(key.getEncoded()));
                } catch (e) {
                    console.log("    Key Details    : [KeyStore Hardware Bound]");
                }
            }

            if (arguments.length > 2 && arguments[2]) {
                var param = arguments[2];
                try {
                    var IvParam = Java.use("javax.crypto.spec.IvParameterSpec");
                    if (param.$className === "javax.crypto.spec.IvParameterSpec") {
                        var casted = Java.cast(param, IvParam);
                        console.log("    IV (Hex)       : " + bytesToHex(casted.getIV()));
                    }
                } catch (e) {}
            }

            return overload.apply(this, arguments);
        };
    });

    // Cipher.doFinal overloads
    var doFinalOverloads = Cipher.doFinal.overloads;
    doFinalOverloads.forEach(function (overload) {
        overload.implementation = function () {
            var result = overload.apply(this, arguments);

            console.log("[*] Cipher.doFinal() called on: " + this.getAlgorithm());
            if (arguments.length > 0 && arguments[0]) {
                var inputBytes = arguments[0];
                console.log("    Input (String) : " + bytesToString(inputBytes));
                console.log("    Input (Hex)    : " + bytesToHex(inputBytes));
            }
            if (result) {
                console.log("    Output (Hex)   : " + bytesToHex(result));
                console.log("    Output (String): " + bytesToString(result));
            }
            return result;
        };
    });

    // 2. Hook javax.crypto.Mac
    try {
        var Mac = Java.use("javax.crypto.Mac");
        Mac.doFinal.overload('[B').implementation = function (input) {
            var out = this.doFinal(input);
            console.log("\n[+] --- Mac.doFinal() ---");
            console.log("    Algorithm : " + this.getAlgorithm());
            console.log("    Input     : " + bytesToString(input));
            console.log("    Digest Hex: " + bytesToHex(out));
            return out;
        };
    } catch (e) {}

    // 3. Hook java.security.KeyStore
    try {
        var KeyStore = Java.use("java.security.KeyStore");
        KeyStore.getKey.implementation = function (alias, password) {
            console.log("\n[+] --- KeyStore.getKey() ---");
            console.log("    Alias: " + alias);
            var key = this.getKey(alias, password);
            if (key) {
                console.log("    Algorithm: " + key.getAlgorithm());
            }
            return key;
        };
    } catch (e) {}
});
"""

NATIVE_HOOKS = r"""
// 4. Native OpenSSL / BoringSSL hooks
try {
    var evpInit = Module.findExportByName(null, "EVP_CipherInit_ex");
    if (evpInit) {
        Interceptor.attach(evpInit, {
            onEnter: function (args) {
                console.log("\n[+] Native EVP_CipherInit_ex() called");
                // args[3] = key, args[4] = iv, args[5] = enc (1/0)
                var enc = args[5].toInt32();
                console.log("    Mode: " + (enc === 1 ? "ENCRYPT" : "DECRYPT"));
            }
        });
    }
} catch (e) {}
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate Frida runtime script for monitoring Android Cryptography."
    )
    parser.add_argument("--out", help="Output file path (default: stdout).")
    parser.add_argument("--native", action="store_true", help="Include native OpenSSL/BoringSSL hooks.")

    args = parser.parse_args()

    content = FRIDA_CRYPTO_TEMPLATE
    if args.native:
        content += NATIVE_HOOKS

    if args.out:
        try:
            with open(args.out, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"[+] Successfully generated Frida script at: {args.out}")
            return 0
        except Exception as e:
            sys.stderr.write(f"Error writing to {args.out}: {e}\n")
            return 2
    else:
        print(content)
        return 0


if __name__ == "__main__":
    sys.exit(main())
